import test from 'node:test';import assert from 'node:assert/strict';import * as wolf from '../server/games/werewolf.js';import * as spy from '../server/games/spyfall.js';
const players=n=>Array.from({length:n},(_,i)=>({id:String(i),name:'Player '+i,avatar:i%8,bot:false}));
const role=(g,r)=>g.players.find(p=>p.role===r);
function configured(roles){const g=wolf.create(players(roles.length),{daySeconds:120},0);g.players.forEach((p,i)=>p.role=roles[i]);return g;}
test('role distributions 4–16 and private snapshots',()=>{for(let n=4;n<=16;n++){const g=wolf.create(players(n),{daySeconds:120},0);assert.equal(g.players.filter(p=>p.role==='werewolf').length,Math.floor(n/4));const seer=role(g,'seer'),v=wolf.view(g,seer.id);assert.equal(v.me.role,'seer');assert.ok(v.players.every(p=>!('role'in p)));assert.ok(!('actions'in v));assert.equal(g.deadline,120000);}});
test('doctor saves wolf victim and seer result is private',()=>{const g=configured(['werewolf','seer','doctor','villager','villager','hunter']);g.phase='night';g.deadline=40000;wolf.act(g,'0','kill','3',1);wolf.act(g,'2','protect','3',1);wolf.act(g,'1','check','0',1);assert.equal(wolf.view(g,'1').me.checks['0'],'werewolf');assert.deepEqual(wolf.view(g,'3').me.checks,{});assert.throws(()=>wolf.act(g,'1','check','4',2),/alreadyActed/);wolf.advance(g,40001);assert.equal(g.players[3].alive,true);assert.deepEqual(g.lastVictims,[]);assert.equal(g.phase,'dawn');});
test('dead players cannot act and wolves cannot kill pack',()=>{const g=configured(['werewolf','werewolf','seer','doctor','villager','villager','villager','hunter']);g.phase='night';assert.throws(()=>wolf.act(g,'0','kill','1'),/invalidAction/);g.players[4].alive=false;assert.throws(()=>wolf.act(g,'4','kill','3'),/dead/);});
test('tied village vote eliminates nobody',()=>{const g=configured(['werewolf','seer','doctor','villager']);g.phase='vote';g.deadline=1;wolf.act(g,'0','vote','1',0);wolf.act(g,'1','vote','0',0);wolf.advance(g,2);assert.equal(wolf.living(g).length,4);assert.equal(g.phase,'nightTransition');assert.equal(g.event.key,'tie');});
test('hunter shot resolves before parity victory',()=>{const g=configured(['werewolf','hunter','villager','villager']);g.players[3].alive=false;g.phase='night';g.deadline=1;wolf.act(g,'0','kill','1',0);wolf.advance(g,2);assert.equal(g.phase,'hunter');assert.equal(g.winner,null);wolf.act(g,'1','shoot','0',3);assert.equal(g.winner,'villagers');assert.ok(wolf.view(g,'2').players.every(p=>p.role));});
test('hunter timeout and wolf parity',()=>{const g=configured(['werewolf','hunter','villager','villager']);g.players[3].alive=false;g.phase='night';g.deadline=1;wolf.act(g,'0','kill','1',0);wolf.advance(g,2);wolf.advance(g,g.deadline+1);assert.equal(g.winner,'werewolves');});
test('spyfall keeps location secret, validates turn and guesses',()=>{const g=spy.create(players(6),{},0),s=spy.view(g,g.spy),local=g.players.find(p=>p.id!==g.spy);assert.equal(s.me.location,null);assert.equal(s.location,null);assert.equal(s.spy,null);assert.ok(spy.view(g,local.id).me.location);assert.throws(()=>spy.act(g,local.id,'guess',g.location.id,1),/invalidAction/);spy.act(g,g.spy,'guess',g.location.id,1);assert.equal(g.winner,'spy');assert.equal(spy.view(g,local.id).spy,g.spy);});
test('spyfall strict majority and wrong accusation',()=>{const g=spy.create(players(4),{},0);const target=g.players.find(p=>p.id!==g.spy).id,accuser=g.players.find(p=>p.id!==target).id;spy.act(g,accuser,'accuse',target,1);const others=g.players.filter(p=>p.id!==accuser);spy.act(g,others[0].id,'verdict',true,2);assert.equal(g.winner,null);spy.act(g,others[1].id,'verdict',true,3);assert.equal(g.winner,'spy');});
test('spyfall correct catch, timeout and accusation expiry',()=>{const g=spy.create(players(4),{},0),p=g.players.find(p=>p.id!==g.spy);spy.act(g,p.id,'accuse',g.spy,1);for(const x of g.players.filter(x=>x.id!==p.id).slice(0,2))spy.act(g,x.id,'verdict',true,2);assert.equal(g.winner,'agents');const h=spy.create(players(4),{},0);spy.act(h,'0','accuse','1',1);spy.advance(h,31000);assert.equal(h.accusation,null);spy.advance(h,480000);assert.equal(h.winner,'spy');});
test('spyfall enforces one question and passes turn to answerer',()=>{const g=spy.create(players(4),{},0);spy.act(g,'0','question',{to:'1',text:'Hot here?'},1);assert.throws(()=>spy.act(g,'0','question',{to:'2',text:'Again?'},2),/wrongTurn/);assert.throws(()=>spy.act(g,'2','answer',null,3),/wrongTurn/);spy.act(g,'1','answer',null,4);assert.equal(g.turn,'1');assert.equal(g.question,null);});
