import {useState} from 'react';import {Eye,EyeOff,Send} from 'lucide-react';import {useI18n} from '../../../hooks/useGame';import {send} from '../../../hooks/useSocket';import {useStore} from '../../../store';
export default function SpyfallGame({game,catalog}){const {t,lang}=useI18n(),{me,busy}=useStore(),[reveal,setReveal]=useState(false),[to,setTo]=useState(''),[question,setQuestion]=useState(''),[guess,setGuess]=useState(''),[accused,setAccused]=useState(''),[confirm,setConfirm]=useState(false);const location=catalog.find(l=>l.id===game.me.location),name=id=>game.players.find(p=>p.id===id)?.name,spy=game.me.role==='spy';
 return <div className="game-panel"><div className="role-card"><span className="role-symbol">{spy?'🕵️':'🧭'}</span><div><span className="eyebrow">{t('yourSecret')}</span><h3>{reveal?(spy?t('roles.spy'):location?.[lang]):t('hiddenRole')}</h3>{reveal&&<p>{spy?t('spyHelp'):game.me.job?.[lang]}</p>}</div><button className="icon-button" aria-label={t(reveal?'hide':'reveal')} onClick={()=>setReveal(!reveal)}>{reveal?<EyeOff size={20}/>:<Eye size={20}/>}</button></div>
 {game.question?<div className="question-card"><span className="eyebrow">{name(game.question.from)} → {name(game.question.to)}</span><p>“{game.question.i18n?.[lang]||game.question.text}”</p>{game.question.to===me&&<><p className="muted">{t('answerHint')}</p><button className="button secondary" disabled={busy} onClick={()=>send('action',{action:'answer'})}>{t('answered')}</button></>}</div>:<><h3>{t('turnOf',{name:name(game.turn)})}</h3>{game.turn===me&&<form onSubmit={async e=>{e.preventDefault();const r=await send('action',{action:'question',target:{to,text:question}});if(r)setQuestion('');}}><label>{t('askWhom')}<select required value={to} onChange={e=>setTo(e.target.value)}><option value="">{t('choosePlayer')}</option>{game.players.filter(p=>p.id!==me).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{t('oneQuestion')}<textarea required maxLength={250} value={question} onChange={e=>setQuestion(e.target.value)} placeholder={t('questionPlaceholder')}/></label><button className="button secondary" disabled={busy||!to||!question.trim()}><Send size={16}/>{t('ask')}</button></form>}</>}
 {game.accusation?<div className="accusation"><h3>{t('accusation',{name:name(game.accusation.target)})}</h3><p>{t('majority',{count:game.accusation.count,total:Math.floor(game.players.length/2)+1})}</p><div className="flex gap-2"><button className={`button ${game.accusation.myVote===true?'primary':'secondary'}`} disabled={busy} onClick={()=>send('action',{action:'verdict',target:true})}>{t('agree')}</button><button className={`button ${game.accusation.myVote===false?'primary':'secondary'}`} disabled={busy} onClick={()=>send('action',{action:'verdict',target:false})}>{t('disagree')}</button></div></div>:<div className="accuse-controls"><label>{t('suspect')}<select value={accused} onChange={e=>setAccused(e.target.value)}><option value="">{t('choosePlayer')}</option>{game.players.filter(p=>p.id!==me).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="button danger" disabled={!accused||busy} onClick={()=>send('action',{action:'accuse',target:accused})}>{t('accuse')}</button></div>}
 {spy&&reveal&&<div className="spy-guess"><label>{t('guessLocation')}<select value={guess} onChange={e=>{setGuess(e.target.value);setConfirm(false);}}><option value="">{t('chooseLocation')}</option>{catalog.map(l=><option key={l.id} value={l.id}>{l[lang]}</option>)}</select></label>{confirm?<><p className="notice">{t('guessWarning')}</p><div className="flex gap-2"><button className="button primary" disabled={busy} onClick={()=>send('action',{action:'guess',target:guess})}>{t('confirmGuess')}</button><button className="button secondary" onClick={()=>setConfirm(false)}>{t('cancel')}</button></div></>:<button className="button primary" disabled={!guess||busy} onClick={()=>setConfirm(true)}>{t('guess')}</button>}</div>}
 <details className="locations"><summary>{t('locationDeck',{count:catalog.length})}</summary><div>{catalog.map(l=><span key={l.id}>{l[lang]}</span>)}</div></details>
 </div>;
}
